### ISSUE TITLE
Cross link to monostable/awesome-electronics

### ISSUE THREAD

**Issue by kasbah** [intajay/open-electronics#3]
Hey, I created a list a while back: https://github.com/monostable/awesome-electronics.

Would you like to cross-link to each other's lists?

**Comment by ajaymnk** [comment]
Check this commit https://github.com/intajay/open-electronics/commit/d1140286ca1d8643a99bbec11f8a357abf823490
Link this repo to your list also.
@kasbah

**Comment by kasbah** [comment]
Sorry it took so long, added it now. https://github.com/monostable/awesome-electronics#other-lists
